# Generated by Django 4.2.23 on 2025-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0004_alter_dataimportsession_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataimportsession",
            name="update_records",
            field=models.BooleanField(
                default=False,
                help_text="如果启用，现有记录将被更新为新数据",
                verbose_name="Update Existing Records",
            ),
        ),
    ]
