# Generated by Django 2.2 on 2019-05-20 12:04

import company.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='公司名称', max_length=100, unique=True)),
                ('description', models.CharField(help_text='公司描述', max_length=500)),
                ('website', models.URLField(blank=True, help_text='公司网站网址')),
                ('address', models.CharField(blank=True, help_text='公司地址', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='联系邮箱地址', max_length=254)),
                ('contact', models.CharField(blank=True, help_text='联系人', max_length=100)),
                ('URL', models.URLField(blank=True, help_text='链接到外部公司信息')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=company.models.rename_company_image)),
                ('notes', models.TextField(blank=True)),
                ('is_customer', models.BooleanField(default=False, help_text='你们向这家公司销售商品吗?')),
                ('is_supplier', models.BooleanField(default=True, help_text='您是否从这家公司购买商品?')),
            ],
            options={
                'verbose_name': 'Company',
            }
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Contact',
            }
        ),
        migrations.CreateModel(
            name='SupplierPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(help_text='供应商库存单位', max_length=100)),
                ('manufacturer', models.CharField(blank=True, help_text='制造商', max_length=100)),
                ('MPN', models.CharField(blank=True, help_text='制造商零件号', max_length=100)),
                ('URL', models.URLField(blank=True, help_text='外部供应商零件链接的URL')),
                ('description', models.CharField(blank=True, help_text='供应商零件描述', max_length=250)),
                ('note', models.CharField(blank=True, help_text='注释', max_length=100)),
                ('base_cost', models.DecimalField(decimal_places=3, default=0, help_text='最低收费（如仓储费）', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('packaging', models.CharField(blank=True, help_text='零部件包装', max_length=50)),
                ('multiple', models.PositiveIntegerField(default=1, help_text='批量订购', validators=[django.core.validators.MinValueValidator(1)])),
                ('minimum', models.PositiveIntegerField(default=1, help_text='最小起订量 (MOQ)', validators=[django.core.validators.MinValueValidator(1)])),
                ('lead_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'part_supplierpart',
                'verbose_name': 'Supplier Part',
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cost', models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricebreaks', to='company.SupplierPart')),
            ],
            options={
                'verbose_name': 'Supplier Price Break',
                'db_table': 'part_supplierpricebreak',
            },
        ),
    ]
