# Generated by Django 2.2.5 on 2019-09-13 14:07

import InvenTree.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_supplierpart_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='URL',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='外部公司信息链接'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='URL',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='外部供应商部件链接的URL'),
        ),
    ]
