# Generated by Django 3.2.16 on 2023-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_alter_supplierpricebreak_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpart',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='最后更新时间', null=True, verbose_name='Updated'),
        ),
    ]
