# Generated by Django 3.2.19 on 2023-05-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0061_remove_supplierpart_pack_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='metadata',
            field=models.JSONField(blank=True, help_text='JSON元数据字段, 供外部插件使用', null=True, verbose_name='Plugin Metadata'),
        ),
    ]
