# Generated by Django 3.2.18 on 2023-05-02 19:56

import InvenTree.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0062_contact_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='描述地址条目的标题', max_length=100, verbose_name='Address title')),
                ('primary', models.BooleanField(default=False, help_text='设置为主地址', verbose_name='Primary address')),
                ('line1', models.CharField(blank=True, help_text='地址行 1', max_length=50, verbose_name='Line 1')),
                ('line2', models.CharField(blank=True, help_text='地址行 2', max_length=50, verbose_name='Line 2')),
                ('postal_code', models.CharField(blank=True, help_text='邮政编码', max_length=10, verbose_name='Postal code')),
                ('postal_city', models.CharField(blank=True, help_text='邮政编码对应的城市', max_length=50, verbose_name='City')),
                ('province', models.CharField(blank=True, help_text='州或省', max_length=50, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, help_text='地址国家', max_length=50, verbose_name='Country')),
                ('shipping_notes', models.CharField(blank=True, help_text='给货运公司的备注', max_length=100, verbose_name='Courier shipping notes')),
                ('internal_shipping_notes', models.CharField(blank=True, help_text='供内部使用的货运备注', max_length=100, verbose_name='Internal shipping notes')),
                ('link', InvenTree.fields.InvenTreeURLField(blank=True, help_text='地址信息链接（外部）', verbose_name='Link')),
                ('company', models.ForeignKey(help_text='选择公司', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='company.company', verbose_name='Company')),
            ],
        ),
    ]
