# Generated by Django 4.2.19 on 2025-02-21 13:46

import InvenTree.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0072_auto_20250221_1236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="地址信息链接（外部）",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="外部公司信息链接",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="公司网站 URL",
                max_length=2000,
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="supplierpart",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="外部供应商零件链接的 URL",
                max_length=2000,
                null=True,
                verbose_name="Link",
            ),
        ),
    ]
