# Generated by Django 3.2.5 on 2021-11-19 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0012_notificationentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.CharField(default=uuid.uuid4, editable=False, help_text='接收此 webhook 的端点', max_length=255, verbose_name='Endpoint')),
                ('name', models.CharField(blank=True, help_text='此 webhook 的名称', max_length=255, null=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='这个webhook是否处于激活状态', verbose_name='Active')),
                ('token', models.CharField(blank=True, default=uuid.uuid4, help_text='访问令牌', max_length=255, null=True, verbose_name='Token')),
                ('secret', models.CharField(blank=True, help_text='HMAC的共享密钥', max_length=255, null=True, verbose_name='Secret')),
                ('user', models.ForeignKey(blank=True, help_text='用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='此消息的唯一标识符', primary_key=True, serialize=False, verbose_name='Message ID')),
                ('host', models.CharField(editable=False, help_text='接收此消息的主机', max_length=255, verbose_name='Host')),
                ('header', models.CharField(blank=True, editable=False, help_text='本消息的标题', max_length=255, null=True, verbose_name='Header')),
                ('body', models.JSONField(blank=True, editable=False, help_text='本消息的内容', null=True, verbose_name='Body')),
                ('worked_on', models.BooleanField(default=False, help_text='这条消息的工作是否已完成?', verbose_name='Worked on')),
                ('endpoint', models.ForeignKey(blank=True, help_text='接收此消息的端点', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.webhookendpoint', verbose_name='Endpoint')),
            ],
        ),
    ]
