# Generated by Django 3.2.16 on 2023-01-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_newsfeedentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationentry',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='最后更新时间', null=True, verbose_name='Updated'),
        ),
    ]
