# Generated by Django 3.2.18 on 2023-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_projectcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='metadata',
            field=models.JSONField(blank=True, help_text='JSON元数据字段，供外部插件使用', null=True, verbose_name='Plugin Metadata'),
        ),
    ]
