# Generated by Django 3.2.23 on 2023-11-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_apitoken_key'),
        ('common', '0021_auto_20230805_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='负责此项目的用户或组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_codes', to='users.owner', verbose_name='Responsible'),
        ),
    ]
