# Generated by Django 4.2.14 on 2024-08-07 22:40

import django.db.models.deletion
from django.db import migrations, models

from common.models import state_color_mappings


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("common", "0028_colortheme_user_obj"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvenTreeCustomUserStateModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.IntegerField(
                        help_text="将在模型数据库中保存的值",
                        verbose_name="Key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="州名",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="在前端显示的标签",
                        max_length=250,
                        verbose_name="Label",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=state_color_mappings(),
                        default="secondary",
                        help_text="在前端显示的颜色",
                        max_length=10,
                        verbose_name="Color",
                    ),
                ),
                (
                    "logical_key",
                    models.IntegerField(
                        help_text="在业务逻辑中等于此自定义状态的状态逻辑键",
                        verbose_name="Logical Key",
                    ),
                ),
                (
                    "reference_status",
                    models.CharField(
                        help_text="由此扩展此自定义状态的状态集",
                        max_length=250,
                        verbose_name="Reference Status Set",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        help_text="与此状态关联的模型",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom State",
                "verbose_name_plural": "Custom States",
                "unique_together": {
                    ("model", "reference_status", "key", "logical_key")
                },
            },
        ),
    ]
