# Generated by Django 4.2.15 on 2024-09-21 06:05

import InvenTree.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0029_inventreecustomuserstatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(help_text='条码数据', max_length=250, verbose_name='Data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='条形码扫描日期和时间', verbose_name='Timestamp')),
                ('endpoint', models.CharField(blank=True, help_text='处理条形码的URL端点', max_length=250, null=True, verbose_name='Path')),
                ('context', models.JSONField(blank=True, help_text='条码扫描的上下文数据', max_length=1000, null=True, verbose_name='Context')),
                ('response', models.JSONField(blank=True, help_text='条码扫描的响应数据', max_length=1000, null=True, verbose_name='Response')),
                ('result', models.BooleanField(default=False, help_text='条码扫描是否成功?', verbose_name='Result')),
                ('user', models.ForeignKey(blank=True, help_text='条码扫描用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Barcode Scan',
            },
            bases=(InvenTree.models.PluginValidationMixin, models.Model),
        ),
    ]
