# Generated by Django 4.2.16 on 2024-11-24 12:41

import django.db.models.deletion
from django.db import migrations, models

import InvenTree.models


class Migration(migrations.Migration):
    dependencies = [
        ('plugin', '0009_alter_pluginconfig_key'),
        ('common', '0031_auto_20241026_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionList',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        help_text='JSON元数据字段，供外部插件使用',
                        null=True,
                        verbose_name='Plugin Metadata',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='选择列表的名称',
                        max_length=100,
                        unique=True,
                        verbose_name='Name',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        help_text='选择列表的描述',
                        max_length=250,
                        verbose_name='Description',
                    ),
                ),
                (
                    'locked',
                    models.BooleanField(
                        default=False,
                        help_text='这个选择列表是否被锁定?',
                        verbose_name='Locked',
                    ),
                ),
                (
                    'active',
                    models.BooleanField(
                        default=True,
                        help_text='这个选择列表可以使用吗?',
                        verbose_name='Active',
                    ),
                ),
                (
                    'source_string',
                    models.CharField(
                        blank=True,
                        help_text='可选字符串，用于标识此列表的来源',
                        max_length=1000,
                        verbose_name='Source String',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='选择列表的创建日期和时间',
                        verbose_name='Created',
                    ),
                ),
                (
                    'last_updated',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='选择列表最后更新的日期和时间',
                        verbose_name='Last Updated',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Selection List',
                'verbose_name_plural': 'Selection Lists',
            },
            bases=(InvenTree.models.PluginValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SelectionListEntry',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'value',
                    models.CharField(
                        help_text='选择列表项的值',
                        max_length=255,
                        verbose_name='Value',
                    ),
                ),
                (
                    'label',
                    models.CharField(
                        help_text='选择列表项的标签',
                        max_length=255,
                        verbose_name='Label',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        help_text='选择列表项的描述',
                        max_length=250,
                        verbose_name='Description',
                    ),
                ),
                (
                    'active',
                    models.BooleanField(
                        default=True,
                        help_text='此选择列表项是否处于活动状态?',
                        verbose_name='Active',
                    ),
                ),
                (
                    'list',
                    models.ForeignKey(
                        blank=True,
                        help_text='归属的列表',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entries',
                        to='common.selectionlist',
                        verbose_name='Selection List',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Selection List Entry',
                'verbose_name_plural': 'Selection List Entries',
                'unique_together': {('list', 'value')},
            },
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='default',
            field=models.ForeignKey(
                blank=True,
                help_text='此选择列表的默认条目',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='common.selectionlistentry',
                verbose_name='Default Entry',
            ),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='source_plugin',
            field=models.ForeignKey(
                blank=True,
                help_text='提供选择列表的插件',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='plugin.pluginconfig',
                verbose_name='Source Plugin',
            ),
        ),
    ]
